# build image that should be used in pipeline-linux.yml
FROM node:20.17.0-alpine3.20

# Update and install git
RUN apk update && apk upgrade && \
	apk add --no-cache git bash tzdata curl jq && \
	# Verify git is installed
	git --version

ENV TZ=Europe/Berlin

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["node"]