# build image that should be used in pipeline-linux.yml
FROM node:20.17.0-alpine3.20

# Update and install git
RUN apk update && apk upgrade && \
    apk add --no-cache git

ENV TZ=Europe/Berlin

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["node"]