# build image that should be used in pipeline-linux.yml
FROM node:22.13.0-alpine3.21

# Update and install git
RUN apk update && apk upgrade && \
    apk add --no-cache git

ENV TZ=Europe/Berlin

ENV TZ=Europe/Berlin

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["node"]