stages:
  - generate-docs
  - lint
  - build
  - test

.node-image-matrix:
  image: 
    name: $BUILD_IMAGE_URL:$NODE_VERSION
  parallel:
    matrix:
      - NODE_VERSION: ["20.17.0", "22.13.0", "24.0.0"]
  cache:
    key:
      files:
        - package-lock.json
      prefix: "node_modules-${NODE_VERSION}"  # separate cache per Node version
    paths:
      - node_modules/
      - .npm
  before_script:
    - |
      echo "Using Node version: $(node -v)"
      npm config set cache .npm
      npm ci --prefer-offline --ignore-scripts


generate-docs:
  stage: generate-docs
  extends: .node-image-matrix
  script:
    - npm run generate-docs && [[ -z "$(git status -s)" ]]

lint:
  stage: lint
  extends: .node-image-matrix
  script:
    - npm run lint

build:
  stage: build
  extends: .node-image-matrix
  artifacts:
    expire_in: 1 hrs
    paths:
      - ./packages/profiler/dist
      - ./packages/profiler-core/dist
      - ./packages/profiler-jest-environment/*.js
      - ./packages/profiler-jest-environment/*.d.ts
      - ./packages/cli/dist
      - ./packages/windows-sensorinterface/dist
  script:
    - npm run build

test:
  stage: test
  extends: .node-image-matrix
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    expire_in: 1 hrs
    paths:
      - ./profiles/jest/accumulated.oak
      - ./profiles/jest/performance.json
  variables:
    OAKLEAN_DISABLE_REGISTRY: true
  script:
    - npm run test-measure
